export const neuEvaporatorModel = {
    phTank6: 0.00,
    feedRateEvaporatorTank3: false,
    phTank3: 0.00,
    phHmiTank3: 0.00,
    waterSampleInBottleTank6: false,
    monthlyCalibrationOfPhMeterTank3: false,
    conductivity: 0.00,
    waterLevelTank6: 0.00,
    flowRateTank6: 0.00,
    waterQualityTank7: false,
    waterLevelTank7: '',
    waterLevelLitreTank8: false,
    anyAbnormalUsageTank8: false,
    waterLevelTank9: false,
    anyAbnormalUsageTank9: false,
};
